name: Lint Build
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  lint-n-build:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: checkout

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
          cache: true

      - run: go mod download
        name: Cache gomod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout 120s
          only-new-issues: false
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
